FROM python:3.9.0

COPY process_stream_server.py /app/process_stream_server.py
COPY n_kafka /app/n_kafka
COPY requirements.txt /app/requirements.txt

# work within directory app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["python","process_stream_server.py"]